import React, { useEffect, useState } from 'react';

interface Props{
}
const PrivacyContainer: React.FC<Props> = ({}) => {


  return (
    <div className="legal" style={{padding: '1rem 0'}}>
	    <h1 className="title" style={{padding: '1rem 0'}}>
	        Privacy Policy
	    </h1>
	    <div>
	        <p style={{padding: '1rem 0'}}><span>Last Updated:&nbsp; Jan 3, 2023<br /></span></p>
	<p>This privacy policy (the "Privacy Policy") describes how PuppySpot Group, LLC ("PuppySpot") handles your personal information. By using any of the sites owned and operated by PuppySpot, including, but not limited to www.puppytube.com, www.rebarkable.com, or <a href="https://www.puppyspotadoption.shop">www.PuppySpotAdoption.shop</a>, and downloading and/or using the PuppySpot mobile application (collectively referred to herein as the "Site"), you consent to the collection, use, storage, processing, transfer, and disclosure of your personal information as described in this Privacy Policy. If you do not agree with the terms of this Privacy Policy, please do not create a profile, use the Site, or use any of the services offered through the Site.</p>
	    </div>
	    <div>
	        <h2 style={{padding: '1rem 0'}}>Information Collection</h2>
	<p>We collect information in order to provide the Site and its services to you and our other users, improve user experience, and to communicate with you and other users about the Site and its services. The information we collect from you, and therefore the applicability of various sections of this Privacy Policy, will depend on your particular interaction with the Site.</p>
	<p><em>Profile Information</em>: In order to create a profile, make submissions or comments, adopt a puppy, receive notifications and/or updates, or request additional information about the Site or the services offered on the Site, we may collect the following information: name, email address, phone number, mobile phone number, physical address and / or zip code, gender, birth date, information about yourself and your family, any additional information you choose to provide such as reviews, comments, video, audio, photographic, written or other content or information.</p>
	<p className="p1"><span className="s1">PuppySpot offers you the option of registering an account with us by logging in with an account you have established with certain third party sites such as, but not limited to, Facebook (hereafter, the “Outside Account”). By logging in via the Outside Account, you are granting PuppySpot the right to access, utilize and store (if applicable) information (including Personal Information) tied to your Outside Account in connection with your use of the Site. Depending on the Outside Account you choose and subject to the privacy settings that you have set in such Outside Account and on your account with PuppySpot, the information you make accessible via your Outside Account (including Personal Information) will be available to PuppySpot and on and through your PuppySpot account.</span></p>
	<p><em>Public Content</em>: The information that you contribute through the Site is intended for public display, including your account profile, username, photos, videos, reviews, and comments. We may display this information through the Site, share it with businesses, use it in promotional materials, and further distribute it to a wider audience at our sole discretion. We are not responsible for the privacy or security of any information that you make publicly available on the Site or what others do with information you share with them on the Site. We are not responsible for the accuracy, use or misuse of any content that you disclose or receive from third parties through the Site.</p>
	<p><em>Purchase Information</em>: When you make a payment on the Site or by phone, you may be asked for financial information such as account or credit card numbers in addition to information about you such as your name, phone number, billing/mailing address and email address as well as any other information you provide us to process your transaction or complete your purchase, including credit card or payment account information. PuppySpot uses this personal and financial information (hereafter, "Personal Information") that you voluntarily provide to us in order to provide you with the services offered through the Site. By making a purchase on the Site, you consent to our providing your Personal Information to our service providers and such third parties as we determine is necessary to process your transaction, such as credit card companies and banking institutions used to process the transaction and breeder(s).</p>
	<p><em>Interaction with the Site</em>: We may store information about your use of the Site, such as your search activity, the pages you view, the date and time of your visit(s), purchases you make through the Site. We also may store information that your computer or mobile device provides to us in connection with your use of the Site, such as your browser type, type of computer or mobile device, browser language, IP address, mobile carrier, phone number, unique device identifier, advertising identifier, location (including geolocation, beacon based location, and GPS location), and requested and referring URLs. You may be able to opt out of our use of certain location data through your device or browser settings. While you may decline to provide certain information to us, it may render you unable to access certain services and features offered through the Site.</p>
	<h2 style={{padding: '1rem 0'}}>Log File and Cookie Information</h2>
	<p><em>Log Files</em>: For all users of the Site, the Site's web server uses an extended log file format which captures: date and time of visit, referring address (location from which a visitor comes to the Site), type of Internet browser, and visitor's IP address. Each computer that connects to the Internet is assigned a unique number, an IP address, for identification purposes. The log file does not capture a user's email address.</p>
	<p><em>Cookies</em>: A cookie is a series of data characters that, when programmed into a website, is placed by the web server into the browser's application folder on your computer. Once placed onto your machine, the cookie will allow the website or certain third parties that we work with to "recall" you as a unique individual. We use cookies on the Site to assist us in providing customized services.</p>
	<p>In addition, we place cookies that collect information about how you use the Site. These cookies aggregate anonymous information regarding how visitors use the Site so that we can improve how the Site works. For example, it will let us, our affiliates and certain third parties that we work with to know which pages visitors go to the most or if our visitors are seeing an error page on our site. We also place cookies to remember the choices you make on the Site so that we and others we work with can provide you with a more enhanced and personalized experience.</p>
	<p>Should you choose to do so, cookies can be removed from your hard drive and certain web browsers can be set so that cookies are not used or saved. Please check with your browser provider for more information on removing cookies. Disabling cookies may restrict your use of the Site and affect the way in which it operates.</p>
	<p>We may from time to time use third party advertising companies to serve ads on our behalf across the Internet. These advertising companies may also collect anonymous information about your visits to the Site. This is primarily accomplished through the use of a technology device, commonly referred to as a Web beacon, cookie or an action tag, which is placed on various Web pages within the Site or in an HTML e-mail that allows the third party advertising company to collect anonymous information. There may also be, from time to time, services offered by external service providers that help you use the Site. If you choose to use these optional services, and in the course of doing so, disclose information to the external service providers, and/or grant them permission to collect information about you, then their use of your information is governed by their privacy policies, if any.</p>
	<p>Notwithstanding any other provision in this policy, in visiting the Site, a third-party advertiser (or its partners) may place or recognize a unique cookie on your browser. These cookies enable more customized ads, content or services to be provided to you. To trigger these cookies, we may pass an encrypted or "hashed" (non-human readable) identifier corresponding to your email address to a Web advertising partner, who may place a cookie on your computer. No personally identifiable information provided to PuppySpot is on, or is included with, these cookies. You may be able to opt-out of these cookies by visiting <span><strong><a href="https://www.aboutads.info/choices/">www.aboutads.info/choices</a></strong></span>, and&nbsp;<span><strong><a href="https://www.networkadvertising.org/choices/">www.networkadvertising.org/choices&nbsp;</a></strong></span>and following their instructions regarding opting out. We are not responsible for the effectiveness of or the compliance with any third parties' opt-out functionality.</p>
	<p>By visiting or using the Site, you may have access to certain third party functionalities, websites, services, and applications that may use tracking technologies to enhance your experience, and provide services and content to you. One of these technologies is a Flash cookie that is embedded in the Adobe Flash Player, which is a web tool that allows rapid development of dynamic content. Adobe Flash cookies may be used in certain situations where we use Flash to provide some content and to remember settings, preferences and usage. They are similar to browser cookies (as described herein) but are managed through a different interface than the one provided by your web browser. You may access Flash management tools from Adobe's web site directly at&nbsp;<span><strong><a href="https://www.macromedia.com/support/documentation/en/flashplayer/help/settings_manager06.html">www.macromedia.com/support/documentation/en/flashplayer/help/settings_manager06.html</a></strong></span>. Please note that if you reject all or some cookies, you may not be able to take full advantage of all offerings on the Site, in particular, those that require you to sign in.</p>
	<p>Except where a user has a registered an account with us, the log files and cookies do not, on their own, allow us to determine the identity of the user. However, as noted above, this information may allow us to determine things like the URL of the website you visited before coming to the Site, the type of browser or mobile device you are using to access the Site, your IP address, language, approximate geographic location, and time zone. We and/or our authorized third party service providers may automatically collect this information when you access and use the Site through the use of electronic tools like log files and cookies. We use non-personally identifiable information to troubleshoot, administer the Site and its services, analyze trends, gather demographic information, comply with applicable law, and cooperate with law enforcement activities. We may also share this information with our authorized third party service providers to measure the overall effectiveness of our online tools, content, and programming.</p>
	<p>For California Users: Various third parties are developing or have developed signals or other mechanisms for the expression of consumer choice regarding the collection of information about an individual consumer's online activities over time and across third-party websites or online services (e.g., browser do not track signals). Currently, we do not monitor or take any action with respect to these signals or other mechanisms. The Site is not presently configured to support Do Not Track ("DNT") signals from web browsers.</p>
	<p></p>
	<h2 style={{padding: '1rem 0'}}>Minors</h2>
	<p>We only operate general audience services and do not use the Site to knowingly collect personal information from children under the age of thirteen (13) that requires parental notice and consent under the Children's Online Privacy Protection Act ("COPPA") without such parental consent. If you are a child under thirteen (13) years of age, in addition to the fact that you are not permitted to use the Site as you are under eighteen (18) years of age (see our&nbsp;<span><strong><a href="/terms-of-use">Terms of Use</a></strong></span>), you are not permitted to send any information about yourself to us through the Site.</p>
	<p>In the event that we become aware that we have collected personal information from any child under the age of thirteen (13), we will dispose of that information in accordance with COPPA and other applicable laws and regulations. If you are a parent or guardian and you believe that your child under the age of thirteen (13) has provided us with personal information without COPPA-required consent, please contact us at <b>support@puppyspotadoption.shop</b></p>
	<p></p>
	<h2 style={{padding: '1rem 0'}}>Use</h2>
	<p>We use your Personal Information and other information we obtain about you to provide you with the services you request, process transactions, verify your identity, communicate with you, improve our marketing and promotional efforts, provide customer support, analyze Site usage, improve the Site and overall experience, troubleshoot problems, customize your experience, inform you about our services and Site updates, measure interest in our sites and services, internal business purposes, resolve disputes and enforce our&nbsp;<span><strong><a href="/terms-of-use">Terms of Use</a></strong></span>.</p>
	<p>We also work with various third parties to improve the Site. In order to do this, we may be required and you authorize us to share certain information about you or your computer with those third parties. In those cases, we require those third parties to abide by this Privacy Policy and / or similarly restrictive terms.</p>
	<p>You agree that we may use your information to contact you and to deliver information to you that, in some cases, is targeted to your interests, such as targeted banner advertisements, administrative notices, product offerings, and communications relevant to your use of the Site.</p>
	<p>If you wish to opt-out of receiving promotional e-mails and marketing information from us, you may do so at the Unsubscribe Link in any of the e-mails you received.&nbsp;Email messages will also provide you with an opportunity to opt-out of receiving this information. Please note, changes to your preferences may not be effective immediately.</p>
	<p></p>
	<h2 style={{padding: '1rem 0'}}>Disclosure - Sharing of Personal Information</h2>
	<p>We may share your information with third parties for a business purpose. &nbsp;When we disclose personal information for a business purpose, we enter a contract that describes the purpose and requires the recipient to both keep that personal information confidential and not use it for any purpose except performing the contract. &nbsp; We will retain your Personal Information for the period necessary to fulfill the purposes outlined in this Privacy Policy unless a longer retention period is required or allowed by law.</p>
	<p>Some of the circumstances under which your information may be shared:</p>
	<ul>
	<li><strong>To provide services offered through the Site:</strong>&nbsp;We may share Personal Information with third party service providers who help with our business operations, including, but not limited to, agents, and others that we use in the ordinary operation of the Site, such as account and billing, marketing and promotion (including sharing of e-mail addresses with Site marketing partners such as Facebook and Google), user experience research and surveys, website hosting and support and maintenance, the breeder you contract or communicate with, the airline or other transportation provider, Pet Insurer or other third party puppy insurance company, the American Kennel Club, and any other parties involved in the sale, transportation, insuring or veterinary care of your puppy or any related or ancillary services. We will only disclose your Personal Information to the extent reasonably required for the limited purpose of the third party evaluating, analyzing, and providing services contracted to us.</li>
	<li><strong>With your consent:</strong>&nbsp;We will share Personal Information with outside companies, organizations, or individuals when we have your consent to do so.</li>
	<li><strong>With advertisers:</strong>&nbsp;We aggregate (gather up data across multiple members' accounts) personally identifiable information and disclose such information in a non-personally identifiable manner to advertisers and other third parties for marketing and promotional purposes. We may use third-party advertising companies to serve ads on our behalf. These companies may employ cookies and action tags (also known as single pixel gifs or web beacons) to measure advertising effectiveness. Please see the above section regarding cookies for further information, including information on sharing hashed email addresses.</li>
	<li><strong>For legal reasons:</strong>&nbsp;We will share user information with outside parties if we have a good-faith belief that access, use, preservation or disclosure of the information is reasonably necessary to meet any applicable law, regulation, legal process or enforceable governmental request; or protect against harm to the rights, property or safety of us, our users or the public as required or permitted by law.</li>
	<li><strong>To provide third party offers:</strong>&nbsp;We reserve the right to offer third party services and products to you based on the preferences that you identify in your registration and at any time thereafter; such offers may be made by our company or by third parties.</li>
	<li><strong>Other corporate entities:</strong>&nbsp;We may share your Personal Information with members of our corporate family who may provide joint or complementary content or services or may help detect or prevent potentially illegal acts. Should we plan to merge or be acquired by another business entity, we may share personal information with the other company and will require that the new combined entity follow this Privacy Policy with respect to your personal information. Further, should PuppySpot file for protection, or have a third party petition filed against it under the bankruptcy code, any assets of the company, including member Personal Information and non-personal information may be sold or transferred, in whole or part to a new entity.</li>
	<li><strong>Sweepstakes, Contests and Promotions.</strong>&nbsp;We may offer sweepstakes, contests, and other promotions (any, a "Promotion") through the Site that may require registration. By participating in a Promotion, you are agreeing to official rules that govern that Promotion, which may contain specific requirements of you, including, allowing the sponsor of the Promotion to use your name, voice and/or likeness in advertising or marketing associated with the Promotion. If you choose to enter a Promotion, Personal Information may be disclosed to third parties or the public in connection with the administration of such Promotion, including, in connection with winner selection, prize fulfillment, and as required by law or permitted by the Promotion's official rules, such as on a winners list.</li>
	<li><strong>Legal Requests:</strong>&nbsp;PuppySpot cooperates with law enforcement inquiries, as well as other third parties to enforce laws. We can (and you authorize us to) disclose any information about you to law enforcement and other government officials as we, in our sole discretion, believe necessary or appropriate, in connection with any investigation of fraud, intellectual property infringements, or other activity that is illegal or may expose us or you to legal liability.</li>
	</ul>
	<p>By accepting this Privacy Policy, you agree that, with respect to other users' personally identifiable information that you obtain through the Site, PuppySpot hereby grants to you a license to use such information only for: (a) Site related communications that are not unsolicited commercial messages, and (b) any other purpose to which such user expressly agrees after complete disclosure of the purpose. In all cases, you must give users an opportunity to remove themselves from your database. In addition, under no circumstances, except as defined in this Privacy Policy, may you disclose personally identifiable information about another user to any third party without our consent and the consent of such other user after adequate disclosure. PuppySpot and our Site users do not tolerate spam. Therefore, without limiting the foregoing, you are not licensed to add a Site user to your mailing list (email or physical mail) or any other advertising or contact list or database without such user's express consent after adequate disclosure. To report spam from other Site users, please&nbsp;<span><strong><a href="/contact">Contact Us</a></strong></span>.</p>
	<p>Federal law gives you the right to limit some but not all sharing. Federal law also requires us to tell you how we collect, share and protect your personal information. Some of the personal information we collect and share depends on the product or service you have with us. This shared information can include: your name, address, phone number and email address. We may share your personal information with third parties for our everyday business purposes, for our marketing purpose, for joint marketing with other companies, and for our affiliates and non-affiliates to market to you.</p>
	<p>If you are a new user, we can begin sharing your information from the date you agree to this agreement. When you are no longer an active user on the Site, we may continue to share your information as described in this notice.</p>
	<p></p>
	<h2 style={{padding: '1rem 0'}}>Security</h2>
	<p>The Site has security measures in place to protect your information. We take reasonable precautions to protect against the loss, misuse and unauthorized access of your personal information under our control. Because the security of your personal information is a high priority, we have taken appropriate&nbsp;steps to ensure that it is processed confidentially, accurately and securely. The Site uses an encryption technology which is supported by the vast majority of modern Internet browsers in order to verify the identity of the transacting servers through certificates and digital signatures, and confirm that message content integrity is maintained throughout its transmission. Unfortunately, no data transmission over the Internet can be guaranteed to be 100% secure. As a result, while we employ commercially reasonable security measures to protect data and seek to partner with service providers which do the same, we cannot guarantee the security of any information transmitted to the Site and are not responsible for the actions of any third parties that may receive any such information.</p>
	<h2 style={{padding: '1rem 0'}}>Data Retention and Requesting Data Deletion</h2>
	<p>We keep your information, such as your name, email address and phone number for as long as you keep your account in existence. &nbsp;In some instances, we will delete the information you provide to us after it is no longer needed. &nbsp;Please note that it may not be possible to delete all copies of information, photographs, or submissions that has been previously shared on our Site.</p>
	<p>To request deletion of your personally identifiable information collected by PuppySpot, please send an email with your request to support@puppyspotadoption.shop. &nbsp;We may deny your deletion request if the retaining the information necessary to complete the transaction for which we collected the personal information, our legitimate business interests, for legal reasons, and to prevent harm to you, any third party, or us. &nbsp;For example, we will keep your personal information if you have purchased a puppy through PuppySpot so that we can continue to provide service for any health claims. &nbsp;</p>
	<p>Only you, or someone you authorize to act on your behalf, may make a request to know or delete your data. An authorized agent may make a request on your behalf by providing written permission signed by you.&nbsp;</p>
	<p>You must provide us with sufficient information for us to reasonably verify that you are the consumer from whom we collected the personal information. Any Personal Information you send us to verify your identity will be used for this purpose only. We will make commercially reasonable efforts to identify your personal information that we collect, process, store, disclose and otherwise use and to respond to your requests. If we are unable to verify your identity or if we suspect fraudulent activity, we may decline to comply with your request.</p>
	<h2 style={{padding: '1rem 0'}}>For Users Outside The United States</h2>
	<p>The Site is hosted on servers located in the United States. If you are a user accessing the Site from the European Union, Australia, Asia, or any other region with laws or regulations governing personal data collection, use, and disclosure, that differ from United States laws, you are transferring your personal information and data to the United States which may not have the same data protection laws as such other regions. By providing user information through the Site, you are consenting to the transfer of your information to the United States for processing and maintenance in accordance with this Privacy Policy and the Terms of Use. You are also consenting to the application of United States law in all matters concerning the Site.</p>
	<h2 style={{padding: '1rem 0'}}>California Privacy Rights</h2>
	<p>We may elect to share information about you with third parties for those third parties' direct marketing purposes. California Civil Code § 1798.83 permits California residents who have supplied personal information (as defined in the law) to us to, under certain circumstances, request and obtain certain information regarding our disclosure, if any, of personal information to third parties for their direct marketing purposes. If this law applies to you, you may obtain the categories of personal information shared by us and the names and addresses of all third parties that received personal information for their direct marketing purposes from us during the immediately prior calendar year (e.g., requests made in 2016 will receive information about 2015 sharing activities). To make such a request, please provide sufficient information for us to determine if this applies to you, attest to the fact that you are a California resident and provide a current California address for our response. To make such a request (limit one request per year), please send, please send a request by email to the Privacy Administrator at <a href="mailto:support@puppyspotadoption.shop" title="mailto:support@puppyspotadoption.shop">support@puppyspotadoption.shop</a> or by postal mail to PuppySpot, Attn: Your California Privacy Rights, c/o Privacy Administrator, P.O. Box 2329, Nutley, NJ 07110. All requests must be labeled "Your California Privacy Rights" on the email subject line or envelope or post card. For all requests, please clearly state that the request is related to "Your California Privacy Rights", include your name, street address, city, state, zip code and e-mail address (your street address is optional if you wish to receive a response to your request via email) and indicate your preference on how our response to your request should be sent (email or postal mail). We will not accept requests via the telephone or by facsimile. We are not responsible for notices that are not labeled or sent properly, or do not have complete information.</p>
	<p>The California Consumer Privacy Act (the “CCPA” or “Act”) provides California residents with specific rights regarding their personal information. You may learn more about your rights under the CCPA <a href="https://oag.ca.gov/privacy/ccpa" rel="follow">here</a></p>
	<h2 style={{padding: '1rem 0'}}>Nevada Privacy Rights</h2>
	<p className="p1">Nevada residents have certain privacy rights as specified under Nevada law.<span className="Apple-converted-space">&nbsp; </span>Our Privacy Policy is consistent with these laws.<span className="Apple-converted-space">&nbsp; </span>We do not sell your covered information as defined under Chapter 603A of the Nevada Revised Statutes.<span className="Apple-converted-space">&nbsp; </span>If you have any questions, please contact us at support@puppyspotadoption.shop.&nbsp;</p>
	<h2 style={{padding: '1rem 0'}}>Copyright</h2>
	<p>All text, graphics, logos, icons, images, audio clips, video clips, and other content of any nature on the Site is the property of PuppySpot or its content suppliers and is protected by U.S. and international copyright laws. The collection, arrangement, and assembly of all content on this Site is the exclusive property of PuppySpot and is protected by U.S. and international copyright laws. Any other use, including the aggregation, posting, reproduction, modification, distribution, transmission, re-publication, display, or performance, of the content on this Site is strictly prohibited.</p>
	<p></p>
	<h2 style={{padding: '1rem 0'}}>Changes To This Privacy Policy</h2>
	<p>PuppySpot reserves the right to change, modify, add or remove portions of this Privacy Policy at any time, so please review it frequently. If PuppySpot decides to change this Privacy Policy, we will post those changes to this page so that you are aware of what information we collect, how we use it, and under what circumstances, if any, we disclose it. By continuing to access or use the Site after those changes become effective, you agree to be bound by the revised Privacy Policy.</p>
	    </div>
	</div>
  );
}

export default PrivacyContainer;
